import paramiko
HOST = "59.110.152.9"; USER = "root"; PASSWORD = "xbu~KiZ+F+&~7!H"
ssh = paramiko.SSHClient()
ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())
ssh.connect(HOST, username=USER, password=PASSWORD, timeout=15)
stdin, stdout, _ = ssh.exec_command("ps -ef | grep -E 'uvicorn|api_server' | grep -v grep")
print("--- uvicorn processes ---")
print(stdout.read().decode())
stdin, stdout, _ = ssh.exec_command("cat /root/0418_qqmj/stop.sh")
print("\n--- stop.sh ---")
print(stdout.read().decode())
stdin, stdout, _ = ssh.exec_command("cat /root/0418_qqmj/server.pid")
print("\n--- server.pid ---")
print(stdout.read().decode())
stdin, stdout, _ = ssh.exec_command("grep -c doubt_count /root/0418_qqmj/schemas.py")
print("\ndoubt_count in schemas.py:", stdout.read().decode().strip())
stdin, stdout, _ = ssh.exec_command("grep -c doubt_count /root/0418_qqmj/fact_engine.py")
print("doubt_count in fact_engine.py:", stdout.read().decode().strip())
stdin, stdout, _ = ssh.exec_command("grep -c doubt_count /root/0418_qqmj/api_server.py")
print("doubt_count in api_server.py:", stdout.read().decode().strip())
ssh.close()
